config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'
  get 'teams/:id', to: 'teams#show', as: :teams_show

  resources :games do
    resources :characters do
      resources :supports
    end
  end

  root 'teams#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
  has_many :supports
  has_many :partners, through: :supports, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :game }
  validates :game, presence: true
  validates :recruitment_chapter, presence: true, numericality: { only_integer: true }
  validates :rating, presence: true, numericality: { only_integer: true }
  validates_with CharacterValidator
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :characters, dependent: :destroy

  validates :name, presence: true
  validates :full_name, presence: true
  validates :difficulty, presence: true, uniqueness: { scope: :name }
  validates :num_chapters, presence: true, numericality: { only_integer: true }
  validates :min_team_size, presence: true, numericality: { only_integer: true }
  validates :max_team_size, presence: true, numericality: { only_integer: true }
  validates_with GameValidator
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :character
  belongs_to :partner, class_name: "Character"

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_support_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_support_options)
  end

  def inverses
    self.class.where(inverse_support_options)
  end

  def inverse_support_options
    { partner_id: character_id, character_id: partner_id }
  end

  validates :character, presence: true, uniqueness: { scope: :partner }
  validates_with SupportValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:id])
  end

  def edit
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:id])
  end

  def create
    @game = Game.find(params[:game_id])
    params[:character][:game_id] = @game.id

    @character = Character.new(character_params)

    if @character.save
      redirect_to game_path(@game)

      # TODO: Bring the optional redirect back if the UI changes to fit it better
      # if helpers.otherCharactersFromTheSameGame(@character).length > 0
      #   redirect_to game_character_path(@game, @character)
      # else
      #   redirect_to game_path(@game) # No point showing character if we can't add supports
      # end
    else
      redirect_to game_path(@game)
    end
  end

  def update
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:id])

    if @character.update(character_params)
      redirect_to game_path(@game)

      # TODO: Bring the optional redirect back if the UI changes to fit it better
      # if helpers.otherCharactersFromTheSameGame(@character).length > 0
      #   redirect_to game_character_path(@game, @character)
      # else
      #   redirect_to game_path(@game) # No point showing character if we can't add supports
      # end
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to game_path(@game)
  end

  private
    def character_params
      params.require(:character).permit(:name, :game_id, :recruitment_chapter, :rating)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game
    else
      render 'new'
    end
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to games_path
  end

  private
    def game_params
      params.require(:game).permit(:name, :full_name, :difficulty, :num_chapters, :min_team_size, :max_team_size)
    end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  def create
    @character = Character.find(params[:character_id])
    @game = Game.find(@character.game_id)

    params[:support][:character_id] = @character.id
    params[:support][:partner_id] = Character.find_by(name: params[:support][:partner_name], game_id: @character[:game_id]).id
    params[:support].delete(:partner_name) # Get rid of extraneous field

    if params[:support][:partner_id] != nil # If there is no character with that name, don't make the support
      @support = @character.supports.create(support_params)
    end

    redirect_to game_character_path(@game, @character)
  end

  def destroy
    @character = Character.find(params[:character_id])
    @game = Game.find(@character.game_id)
    @support = @character.supports.find(params[:id])
    @support.destroy

    redirect_to game_character_path(@game, @character)
  end

  private
    def support_params
      params.require(:support).permit(:character_id, :partner_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @characters = Character.all.select { |c| c.game_id == params[:id].to_i }
      .sort { |c1, c2| [c2.rating, c1.recruitment_chapter, c1.id] <=> [c1.rating, c2.recruitment_chapter, c2.id] }
      .as_json(include: { partners: { only: [:name, :id] } },
                                      only: [:name, :id, :recruitment_chapter, :rating])
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def otherCharactersFromTheSameGame(character)
    return Character.all.select { |c| c.game_id == character.game_id }
                        .reject { |c| c.name == character.name }
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
  include CharactersHelper

  def hasNoAvailableSupports?(character)
    return otherCharactersFromTheSameGame(character)
            .reject { |c| character.partners.include? c }
            .length == 0
  end

  def availableSupports(character)
    return otherCharactersFromTheSameGame(character)
            .reject { |c| character.partners.include? c }
            .collect { |c| c.name }
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: [ @game, characterMethod ]) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :recruitment_chapter %><br>
    <%= form.number_field :recruitment_chapter, min: 1, max: @game.num_chapters %>
  </p>
  <p>
    <%= form.label :rating %><br>
    <%= form.number_field :rating, min: 1, max: 5 %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/characters/edit.html.erb
<h1>Edit character</h1>

<%= render 'form', characterMethod: @character %>

<%= link_to 'Back', game_path(@game) %>

app/views/characters/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>
<p>
  <strong>Recruitment chapter:</strong>
  <%= @character.recruitment_chapter %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @character.rating %>
</p>

<h2>Supports</h2>
<%= render @character.supports %>

<h2>Add a support:</h2>
<%= render 'supports/form' %>

<%= link_to 'Edit', edit_game_character_path(@game, @character) %> |
<%= link_to 'Back', game_path(@game) %>

app/views/games/_form.html.erb
<%= form_with model: @game, local: true do |form| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this character from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name %>
  </p>

  <p>
    <%= form.label :difficulty %><br>
    <%= form.text_field :difficulty %>
  </p>

  <p>
    <%= form.label :num_chapters, "Number of chapters" %><br>
    <%= form.number_field :num_chapters, min: 1 %>
  </p>

  <p>
    <%= form.label :min_team_size, "Recommended min. team size" %><br>
    <%= form.number_field :min_team_size, min: 1 %>
  </p>

  <p>
    <%= form.label :max_team_size, "Recommended max. team size" %><br>
    <%= form.number_field :max_team_size, min: 1 %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/games/edit.html.erb
<h1>Edit game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing Games</h1>
<%= link_to 'New game', new_game_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Full name</th>
    <th>Difficulty</th>
    <th colspan="3"></th>
  </tr>

  <% @games.each do |game| %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.full_name %></td>
      <td><%= game.difficulty %></td>
      <td><%= link_to 'Show', game_path(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>
<p>
  <strong>Full name:</strong>
  <%= @game.full_name %>
</p>
<p>
  <strong>Difficulty:</strong>
  <%= @game.difficulty %>
</p>
<p>
  <strong>Number of chapters:</strong>
  <%= @game.num_chapters %>
</p>
<p>
  <strong>Min. team size:</strong>
  <%= @game.min_team_size %>
</p>
<p>
  <strong>Max. team size:</strong>
  <%= @game.max_team_size %>
</p>

<h2>Characters</h2>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>

  <% @game.characters.each do |character| %>
    <tr>
      <td><%= character.name %></td>
      <td><%= link_to 'Show', game_character_path(@game, character) %></td>
      <td><%= link_to 'Edit', edit_game_character_path(@game, character) %></td>
      <td><%= link_to 'Destroy', game_character_path(@game, character),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<h2>Add a character:</h2>
<%= render 'characters/form', characterMethod: @game.characters.build %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fire Emblem Team Builder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/supports/_form.html.erb
<%= form_with(model: [ @game, @character, @character.supports.build ]) do |form| %>
  <p>
    <%= form.label :partner_name %><br>
    <%= form.select :partner_name, availableSupports(@character) %>
  </p>
  <p>
    <%= form.submit options={ disabled: hasNoAvailableSupports?(@character) } %>
  </p>
<% end %>

app/views/supports/_support.html.erb
<p>
  <strong>Partner:</strong>
  <%= support.partner.name %>
  <%= link_to 'Destroy', game_character_support_path(@game, @character, support),
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
</p>